# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/db/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = { only_tables = [
    "areas",
    "artist_search_cache",
    "artists",
    "audiobook_search_cache",
    "audiobooks",
    "chapters",
    "episodes",
    "podcast_search_cache",
    "podcast_trending_cache",
    "podcasts",
    "recording_search_cache",
    "recordings",
    "release_group_search_cache",
    "release_groups",
    "release_search_cache",
    "releases",
] }

[migrations_directory]
dir = "migrations"
